### ISSUE TITLE
3D Metric Computation when number of predicted contours < number of GT contours

### ISSUE THREAD

**Issue by tdowrick** [sharib-vision/P2ILF#1]
I have been trying to run the evaluation metrics for the 3D data, and have been getting an error when the number of contours in the predicted data is less than the number of contours in the GT data.

https://github.com/sharib-vision/P2ILF/blob/bff3bd1d9255c35f4211fab73b692ddc4132ae35/metrics_new_docker/3D_contour_metrics_v2.py#L92-L97

`ctypeD_names_eval[idx]` will give an index out of range error if `len(ctypeD_names) > len(ctypeD_names_eval)`

The particular case I have had a problem, is where there is only 1 predicted ridge contour, but there are 2 GT ridge contours, as below.
```
{"numOfContours": 2,

 "contour": 

[{"contourType": "Ridge", "modelPoints": {"vertices": [...]}}, 
{"contourType": "Ligament", "modelPoints": {"vertices": [...]}}]
}
```

```
{"numOfContours": 2,

 "contour": 

[{"contourType": "Ridge", "modelPoints": {"vertices": [...]}},
[{"contourType": "Ridge", "modelPoints": {"vertices": [...]}}, 
{"contourType": "Ligament", "modelPoints": {"vertices": [...]}}]
}
```

@sharib-vision

**Comment by sharib-vision** [comment]
Hi @tdowrick, 

Thank for reporting this. 

Try this: https://github.com/sharib-vision/P2ILF/commit/b758d1b18ccf6a69a1f24051513b4be751680b60

**Comment by sharib-vision** [comment]
Also thanks to @espinely  for helping with fixing this bug. Code link here:
https://github.com/sharib-vision/P2ILF/blob/main/metrics_new_docker/contour_metrics_3D.py
